---
- name: Install jenkins and required s/w's
  hosts: 172.31.21.27
  tasks:
    - name: Install jdk
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
    - name: Install git 
      apt:
        name: git
        state: present
        update_cache: yes
    - name: Install MAVEN
      apt:
        name: maven
        state: present
        update_cache: yes
    - name: Download Jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.452.1/jenkins.war
        dest: /home/ubuntu
...
